### ISSUE TITLE
A9 dataset for monocular 3D object detection

### ISSUE THREAD

**Issue by johannes-tum** [tum-traffic-dataset/tum-traffic-dataset-dev-kit#3]
Hi, I would be interest in using your dataset for monocular 3D object detection. However, I noticed that unfortunately you provide mostly bounding box corner points projected onto the image. That's what I found: 

a9_dataset_r00_s00: ca. 800 images, but only projected bboxes
a9_dataset_r00_s01: ca. 200 images, projected bboxes + location
a9_dataset_r00_s02: ca. 60 images, projected bboxes + location
a9_dataset_r01_s01: ca. 1500 images, but only projected bboxes
a9_dataset_r01_s01: ca. 1500 images, but only projected bboxes
a9_dataset_r01_s03: ca. 3000 images, but only projected bboxes

Would you also be able to provide full 3D informationframe for all these cases? With that I would mean: 
- 3D dimension (height, width, length)
- 3D location in camera frame (X, Y, Z)
- 3D rotation. Ideally the rotation matrix in camera frame.

**Comment by walzimmer** [comment]
Hi Johannes,

for monocular 3D object detection please use the sequences below. They contain 3D bounding boxes (3D location, 3D dimensions and yaw rotation):

TUM Traffic Highway Dataset:  Sequence `a9_dataset_r00_s01` and `a9_dataset_r00_s02`.
- contains 642 labeled images with 11,355 labeled 3D bounding boxes

TUM Traffic Intersection Dataset: Sequence `a9_dataset_r02_s01`, `a9_dataset_r02_s02`, `a9_dataset_r02_s03`, and `a9_dataset_r02_s04`.
- contains 4,800 labeled images with 62,396  labeled 3D bounding boxes

Best,
Walter
